spring:
  datasource:
    url: jdbc:h2:file:./data/railstockdb   # speichert DB in ./data/railstockdb.mv.db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # Tabellen automatisch erzeugen/aktualisieren
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console   # erreichbar unter http://localhost:8080/h2-console